### ISSUE TITLE
Delta vs assumptions

### ISSUE THREAD

**Issue by crnkjck** [FMFI-UK-1-AIN-412/tableauEditor#33]
It’s possible to derive a closed tableau from a satisfiable set of signed formulas.

For instance, S⁺ = { F ∀x P(x), T P(a) } is satisfiable, but one can derive:

1. F ∀x P(x) S⁺
2. F P(a) δ { x ↦ a }
3. T P(a) S⁺

The instance of δ would be prohibited in theory if _a_ were a constant, but the tableau editor cannot distinguish constants from variables. However, even in theory, our current definitions do not prohibit _a_ to be a variable.

Either way, this can be fixed by S⁺ being a real rule with validation which would not pass if a free variable in the newly introduced formula has been used in the δ rule in the branch above.

**Comment by crnkjck** [comment]
@MatejKomlossy, would you be willing to implement this?

**Comment by MatejKomlossy** [comment]
Yes I will
